version: "3.8"
services:
  db:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
  up:
    image: ukbackend
    container_name: project-uek223
    env_file: .env
    ports:
      - 8101:8101